add_newline = true

[package]
disabled = true

[aws]
style = "bold yellow"
symbol = "â˜ï¸  "
displayed_items = "all"
format = "on [$symbol$region]($style) "

[kubernetes]
style = "bright-blue bold"
disabled = false
symbol = "â˜¸ï¸  "

[kubernetes.context_aliases]
"<AWS_EKS_CLUSTER_ARN>/<AWS_EKS_CLUSTER_LIVE>"    = "eks:live(âš ï¸ )"
"<AWS_EKS_CLUSTER_ARN>/<AWS_EKS_CLUSTER_STAGING>" = "eks:staging(ğŸ’)"
"<AWS_EKS_CLUSTER_ARN>/<AWS_EKS_CLUSTER_TEST>"    = "eks:test(ğŸ§ª)"
"<AWS_EKS_CLUSTER_ARN>/<AWS_EKS_CLUSTER_DEV>"     = "eks:dev(ğŸ‘©â€ğŸ’»)"

[terraform]
disabled = true
